---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: secureblue-niri-dms-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/secureblue/silverblue-main-hardened
image-version: 44 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - name: atim/starship
          chroot: fedora-44-x86_64
        - name: avengemedia/dms-git
          chroot: fedora-44-x86_64
        - name: avengemedia/danklinux
          chroot: fedora-44-x86_64
    install:
      packages:
        - starship
        - nu
        - niri
        - dms
        - dms-greeter
        - greetd
        - greetd-selinux
        - dgop
        - dsearch
        - alacritty
  - type: systemd
    system:
      enabled:
        - greetd.service
      disabled:
        - gdm.service
  - type: brew
    auto-update: true
    auto-upgrade: true
    update-interval: "1d"
    upgrade-interval: "1d"
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        repo:
          title: "Flathub (system)"
        # If no repo information is specified, Flathub will be used by default
        install:
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - io.missioncenter.MissionCenter
          - com.github.rafostar.Clapper
          - org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages
        repo:
          title: "Flathub (user)"
  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono
        - Terminus
        - Hack
        - NerdFontsSymbolsOnly
        - SourceCodePro
      google-fonts:
        - Roboto
        - Open Sans
        - Inter
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
